alter table Artifact drop constraint if exists fk_Artifact__ConceptDelegate_id;
alter table Concept drop constraint if exists fk_Concept__Concept_id;
alter table ConceptName drop constraint if exists uc_ConceptName_name;
alter table ConceptDelegate drop constraint if exists fk_ConceptDelegage__Concept_id;
alter table ConceptName drop constraint if exists fk_ConceptName__Concept_id;
alter table History drop constraint if exists fk_History__ConceptDelegate_id;
alter table LinkRealization drop constraint if exists fk_LinkRealization__ConceptDelegate_id;
alter table LinkTemplate drop constraint if exists fk_LinkTempate__ConceptDelegate_id;
alter table Media drop constraint if exists fk_Media__ConceptDelegate_id;
alter table SectionInfo drop constraint if exists fk_SectionInfo__ConceptDelegate_id;
alter table Usage drop constraint if exists fk_Usage__ConceptDelegate_id;
alter table UserAccount drop constraint if exists uc_UserAccount_UserName;
drop table if exists Artifact;
drop table if exists Concept;
drop table if exists ConceptDelegate;
drop table if exists ConceptName;
drop table if exists History;
drop table if exists LinkRealization;
drop table if exists LinkTemplate;
drop table if exists Media;
drop table if exists Prefs;
drop table if exists SectionInfo;
drop table if exists UniqueID;
drop table if exists Usage;
drop table if exists UserAccount;